name: Mirror Bitbucket to GitHub

on:
  push:
    branches:
      - main  # Monitors changes to the 'main' branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Configure Git to Use Bitbucket Token
      run: |
        git config user.email 9fgvzeelkpi5q5im5blgcew51x3w93@bots.bitbucket.org

    - name: Clone Bitbucket Repository
      run: |
        git clone --mirror https://bitbucket.org/kevintuei/first-migration.git bitbucket-repo

    - name: Push to GitHub Repository
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd bitbucket-repo
        git remote add github https://github.com/kevshakes/first-migration.git
        git push --mirror github
